"""initial mvp v1.4

Revision ID: 74eabd402284
Revises: 
Create Date: 2026-08-28 18:45:43.497919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74eabd402284'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_margin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('hourly_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocable_fixed_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('productive_minutes_month', sa.Integer(), nullable=False),
    sa.Column('pix_fee_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('card_fee_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('risk_window_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('BUSINESS', 'PERSONAL_WITHDRAWAL', name='expensekind'), nullable=False),
    sa.Column('description', sa.String(length=220), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_company_id'), 'expenses', ['company_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('current_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_company_id'), 'materials', ['company_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_company_id'), 'outbox_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labor_minutes', sa.Integer(), nullable=False),
    sa.Column('expected_loss_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('standard_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'OPERATIONAL', name='role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_company_id'), 'audit_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('tx_type', sa.Enum('PURCHASE_IN', 'PRODUCTION_OUT', 'LOSS_OUT', 'TEST_OUT', 'GIFT_OUT', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'RETURN_IN', name='inventorytxtype'), nullable=False),
    sa.Column('qty_signed', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_company_id'), 'inventory_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_material_id'), 'inventory_transactions', ['material_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('commercial_status', sa.Enum('DRAFT', 'CONFIRMED', 'CANCELLED', name='commercialstatus'), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_charged', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('company_freight_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_payment_method', sa.Enum('PIX', 'CARD', 'CASH', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('fulfillment_method', sa.Enum('PICKUP', 'LOCAL_DELIVERY', 'SHIPPING', 'OTHER', name='fulfillmentmethod'), nullable=False),
    sa.Column('original_promised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_promised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('margin_override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_company_id'), 'purchases', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchases_number'), 'purchases', ['number'], unique=False)
    op.create_table('technical_sheet_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'material_id', 'version', name='uq_sheet_material_version')
    )
    op.create_index(op.f('ix_technical_sheet_items_material_id'), 'technical_sheet_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_technical_sheet_items_product_id'), 'technical_sheet_items', ['product_id'], unique=False)
    op.create_table('fulfillments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.Enum('PICKUP', 'LOCAL_DELIVERY', 'SHIPPING', 'OTHER', name='fulfillmentmethod'), nullable=False),
    sa.Column('status', sa.Enum('WAITING_PRODUCTION', 'READY_FOR_PICKUP', 'READY_FOR_DELIVERY', 'READY_TO_SHIP', 'OUT_FOR_DELIVERY', 'POSTED', 'PICKED_UP', 'DELIVERED', 'CANCELLED', name='fulfillmentstatus'), nullable=False),
    sa.Column('original_promised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_promised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillments_order_id'), 'fulfillments', ['order_id'], unique=True)
    op.create_table('goods_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_purchase_id'), 'goods_receipts', ['purchase_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('PIX', 'CARD', 'CASH', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reversed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'READY', 'BLOCKED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='productionstatus'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_order_id'), 'production_orders', ['order_id'], unique=True)
    op.create_table('promise_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('previous_promised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_promised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promise_changes_order_id'), 'promise_changes', ['order_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_purchase_id'), 'purchase_items', ['purchase_id'], unique=False)
    op.create_table('cost_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('materials_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fixed_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expected_loss_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('integrity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_snapshots_order_id'), 'cost_snapshots', ['order_id'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fulfillment_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fulfillment_id'], ['fulfillments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_fulfillment_id'), 'delivery_attempts', ['fulfillment_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_item_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['purchase_item_id'], ['purchase_items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_items_receipt_id'), 'goods_receipt_items', ['receipt_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('production_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', 'material_id', name='uq_reservation_production_material')
    )
    op.create_index(op.f('ix_inventory_reservations_material_id'), 'inventory_reservations', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_production_id'), 'inventory_reservations', ['production_id'], unique=False)
    op.create_table('material_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('production_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('required_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', 'material_id', name='uq_production_material')
    )
    op.create_index(op.f('ix_material_requirements_material_id'), 'material_requirements', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_requirements_production_id'), 'material_requirements', ['production_id'], unique=False)
    op.create_table('production_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('production_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_exceptions_production_id'), 'production_exceptions', ['production_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_exceptions_production_id'), table_name='production_exceptions')
    op.drop_table('production_exceptions')
    op.drop_index(op.f('ix_material_requirements_production_id'), table_name='material_requirements')
    op.drop_index(op.f('ix_material_requirements_material_id'), table_name='material_requirements')
    op.drop_table('material_requirements')
    op.drop_index(op.f('ix_inventory_reservations_production_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_material_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_goods_receipt_items_receipt_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index(op.f('ix_delivery_attempts_fulfillment_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_cost_snapshots_order_id'), table_name='cost_snapshots')
    op.drop_table('cost_snapshots')
    op.drop_index(op.f('ix_purchase_items_purchase_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_promise_changes_order_id'), table_name='promise_changes')
    op.drop_table('promise_changes')
    op.drop_index(op.f('ix_production_orders_order_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_goods_receipts_purchase_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_fulfillments_order_id'), table_name='fulfillments')
    op.drop_table('fulfillments')
    op.drop_index(op.f('ix_technical_sheet_items_product_id'), table_name='technical_sheet_items')
    op.drop_index(op.f('ix_technical_sheet_items_material_id'), table_name='technical_sheet_items')
    op.drop_table('technical_sheet_items')
    op.drop_index(op.f('ix_purchases_number'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_company_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_inventory_transactions_material_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_company_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_company_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_company_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_materials_company_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_expenses_company_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('companies')
    # ### end Alembic commands ###
